### ISSUE TITLE
[Expo] Its possible ability on Expo?

### ISSUE THREAD

**Issue by wesvh** [chrfalch/react-native-worklets#100]
I am currently facing an issue in my SDK 47 Expo environment while trying to declare a native Expo module to use with an AsyncFunction in my demanding task. After an intensive search, I came across this alternative solution that seems to be exactly what I need. However, I am encountering difficulties with installing and using the library in my Expo environment. The problem arises when integrating it within Babel, as it appears to not be functioning correctly.

**Comment by bglgwyng** [comment]
I migrated my bare react-native application to expo one, and it's working well.
Could you share your error message?

**Comment by wesvh** [comment]
Hello, thank you very much for your interest.

In a moment I attach the error message that I present in babel. But additionally, then I would also like to know how to install it properly, following up on the issues, I found this question,  and I realized that version 0.0.1 alpha is also installed, could it have something to do with it? #97

**Comment by fabio-alss-freitas** [comment]
From what I've tested, it works perfectly with Expo, but the installation command is applying the wrong version. As a temporary solution, I did the following:

Installation via:
`npm install chrfalch/react-native-worklets#main`

Import via:
`import { Worklets } from "react-native-worklets/src"`

**Comment by wesvh** [comment]
Cuando intente compilar en el cliente de desarrollo, devuélveme eso 
![ imagen](https://github.com/chrfalch/react-native-worklets/assets/65504680/e880ccaa-1cb3-4af1-9443-c84ce71c1f66) 

Y  if corro sin compilar. ![ imagen](https://github.com/chrfalch/react-native-worklets/assets/65504680/075d14c8-bc2a-41f2-8c7d-1adafd8930b6)

**Comment by DavidMaza** [comment]
> Cuando intente compilar en el cliente de desarrollo, devuélveme eso ![ imagen](https://user-images.githubusercontent.com/65504680/244479621-e880ccaa-1cb3-4af1-9443-c84ce71c1f66.png)
> 
> Y if corro sin compilar. ![ imagen](https://user-images.githubusercontent.com/65504680/244479789-075d14c8-bc2a-41f2-8c7d-1adafd8930b6.png)

I had the same problem and error message. For the solution, see: https://github.com/margelo/react-native-worklets-core/issues/126#issuecomment-1781111344
