### ISSUE TITLE
android build error : Invalid value for "PACKAGE_PATH": Directory "/Users/vedaxm1/Documents/Work/VedaxLink/node_modules/react-native-worklets/android/build/intermediates/prefab_package_configuration/debug/prefab" is not readable.

### ISSUE THREAD

**Issue by fukemy** [chrfalch/react-native-worklets#101]
can u help? IOS work normally:
```
"react-native-worklets": "github:chrfalch/react-native-worklets#d62d76c",
```

**Comment by fukemy** [comment]
why close without any explain????

**Comment by mrousavy** [comment]
The library is not yet ready for production use and your issue does not include a reproduceable example. For me, it works.

**Comment by FaithfulAudio** [comment]
@mrousavy Hello Sir, I'm on the new React Native Beta IDE testing, and on simulator I'm getting the same error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-vision-camera:configureCMakeDebug[arm64-v8a]'.
> [CXX1429] error when building with cmake using /Users/collinschneide/works-mobile-app/Works.MobileApp/node_modules/react-native-vision-camera/android/CMakeLists.txt: C++ build system [prefab] failed while executing:
      /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java \
        --class-path \
        /Users/collinschneide/.gradle/caches/modules-2/files-2.1/com.google.prefab/cli/2.0.0/f2702b5ca13df54e3ca92f29d6b403fb6285d8df/cli-2.0.0-all.jar \
        com.google.prefab.cli.AppKt \
        --build-system \
        cmake \
        --platform \
        android \
        --abi \
        arm64-v8a \
        --os-version \
        21 \
        --stl \
        c++_shared \
        --ndk-version \
        25 \
        --output \
        /var/folders/xj/j66tk0n57wq1dz_s7pl8ck080000gn/T/agp-prefab-staging6319490872677725551/staged-cli-output \
        /Users/collinschneide/.gradle/caches/transforms-3/0d1c89d20dd96a557c4ad24dcfcf2efa/transformed/jetified-react-android-0.73.8-debug/prefab \
        /Users/collinschneide/.gradle/caches/transforms-3/d6945b7c51d3cb89dddf424c77ef2164/transformed/jetified-fbjni-0.5.1/prefab \
        /Users/collinschneide/works-mobile-app/Works.MobileApp/node_modules/react-native-worklets-core/android/build/intermediates/prefab_package/debug/prefab
    from /Users/collinschneide/works-mobile-app/Works.MobileApp/node_modules/react-native-vision-camera/android
  Usage: prefab [OPTIONS] PACKAGE_PATH...
  
  Error: Invalid value for "PACKAGE_PATH": Directory "/Users/collinschneide/works-mobile-app/Works.MobileApp/node_modules/react-native-worklets-core/android/build/intermediates/prefab_package/debug/prefab" is not readable.
  
Google Pixel 7 emulator on Android 34 SDK with Google Play Services
This doesn't happen on a physical device as far as I'm aware

./gradlew -x lint -PreactNativeArchitectures=arm64-v8a clean assembleDebug --init-script /Users/collinschneide/.vscode/extensions/swmansion.react-native-ide-0.0.10-beta/lib/android/initscript.gradle --stacktrace --info

This is the command being run by the IDE

When inspecting the library, the build intermediates file being looked for doesn't generate.
