### ISSUE TITLE
 Unable to find a specification for `react-native-worklets` depended upon by `VisionCamera`

### ISSUE THREAD

**Issue by patras1** [chrfalch/react-native-worklets#106]
Hi,
I'm trying to install the react-native-vision-camera V3

After installing those:
yarn add react-native-vision-camera@3.0.0-rc.3
yarn add react-native-worklets@https://github.com/chrfalch/react-native-worklets#3ac2fbb
yarn add yarn add @shopify/react-native-skia@0.1.197

but when I'm trying to run "npm i  react-native-worklets@https://github.com/chrfalch/react-native-worklets#3ac2fbb"
I get " no match found ..."

trying to run only "npm i  react-native-worklets"
its finish the installation.

but when I'm trying to run pod install but I get the error:

[!] Unable to find a specification for `react-native-worklets` depended upon by `VisionCamera`
You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Can someone help me with that?
Thanks

**Comment by eisodev** [comment]
See docs here:
https://www.react-native-vision-camera.com/docs/guides#:~:text=(Optional)%20If%20you%20want%20to%20use%20Frame%20Processors%2C%20you%20need%20to%20install%20react%2Dnative%2Dworklets%2Dcore%201.0.0%20or%20higher.

And you need to install this package if you need frame processors (linked in above highlight):
https://github.com/margelo/react-native-worklets-core
