### ISSUE TITLE
SEO issues with this project

### ISSUE THREAD

**Issue by rpopovici** [chrfalch/react-native-worklets#45]
I tried to do a search for `react native worklets` on google and nothing comes up. The only way I was able to find it, was by searching directly on github..

Also the npm repo https://www.npmjs.com/package/react-native-worklets seems unmaintained. There is no link back to this repository.

**Comment by mrousavy** [comment]
That's because it's not released yet. We're still actively working on it. The npm package is actually not by us, but by software mansion. They need that name apparently
