### ISSUE TITLE
JsiConsoleDecorator EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by azimgd** [chrfalch/react-native-worklets#91]
Hey @chrfalch, awesome work!

I get the following error when using rn-worklets in my custom JSI module:
```
com.facebook.react.JavaScript (15): EXC_BAD_ACCESS (code=1, address=0xb0c654aab240)
```

Error above points to a `.global` method being inaccessible here, for which wrapping with a check fixes the problem:
https://github.com/chrfalch/react-native-worklets/blob/d62d76c20ed7a3bbfebe5623bc976e5c2d9beabd/cpp/decorators/WKTJsiConsoleDecorator.h#L135

Here is a simplified usage snippet:
```cpp
#include <thread>
#import "WKTJsiWorkletContext.h"
#import "WKTJsiWorklet.h"

void setup(Runtime &jsRuntime, shared_ptr<CallInvoker> jsCallInvoker) {
  auto workletContext = std::make_shared<RNWorklet::JsiWorkletContext>("MyLibrary");
  auto runOnJS = [jsCallInvoker](std::function<void()>&& f) {};
  auto runOnWorklet = [](std::function<void()>&& f) {};
  workletContext = std::make_shared<RNWorklet::JsiWorkletContext>("MyLibrary");
  workletContext->invokeOnWorkletThread([=](RNWorklet::JsiWorkletContext*, Runtime &rt) {});
}
```

Thanks!

**Comment by azimgd** [comment]
I just noticed that I missed context initialization in the snippet above. Adding that builds successfully but hangs the application, preventing it to start:

<img width="280" alt="Screen Shot 2023-02-21 at 23 49 41" src="https://user-images.githubusercontent.com/4882133/220433116-4ce4c7f8-b23b-4187-8686-1650cf9cfbb6.png">

```cpp
workletContext->initialize("MyLibrary", jsRuntime, runOnJS, runOnWorklet);
```

**Comment by chrfalch** [comment]
Hi @azimgd - sorry for the delay and thanks for the nice words! Are you able to run with RN Worklets now? If so maybe we can close this issue.

**Comment by azimgd** [comment]
Hey Christian. I still have these errors mentioned above.

**Comment by chrfalch** [comment]
Could you try to create a very small reproduction project on Github and share with me and I'll take a look?

**Comment by azimgd** [comment]
here you go: https://github.com/azimgd/workletissue/blob/main/cpp/react-native-workletissue.cpp

Thanks!

**Comment by NathHorrigan** [comment]
Hi, I've experienced both issues here (hang and BAD_ACCESS). What did you do to fix it?
