### ISSUE TITLE
[Question] How to install this package?

### ISSUE THREAD

**Issue by muhamad-rizki** [chrfalch/react-native-worklets#96]
Hi, first of all thanks for this nice library, I have following instruction on README to install on my apps but got wrong package installed (https://www.npmjs.com/package/react-native-worklets) I think it is wrong package? does `react-native-worklets` is available on npm registry ?

**Comment by rkstar** [comment]
can confirm! `yarn add react-native-worklets` installs the wrong package. there is no `lib` directory, no type defs, and the version it installs is `0.0.1-alpha`

**Comment by wesvh** [comment]
From what I've tested, it works perfectly with Expo, but the installation command is applying the wrong version. As a temporary solution, I did the following:

Installation via:
`npm install chrfalch/react-native-worklets#main`

Import via:
`import { Worklets } from "react-native-worklets/src"`

_Originally posted by @fabio-alss-freitas in https://github.com/chrfalch/react-native-worklets/issues/100#issuecomment-1576835293_
